download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip", destfile = "/Users/iakobnikoleishvili/Desktop/Data Science/R/Directory for Class/File.zip", method = "curl")
unzip("File.zip")
Features <- read.table("UCI HAR Dataset/features.txt", col.names = c("N","Functions"))
Activities <- read.table("UCI HAR Dataset/activity_labels.txt", col.names = c("Code", "Activity"))
Subject_test <- read.table("UCI HAR Dataset/test/subject_test.txt", col.names = "Subject")
X_test <- read.table("UCI HAR Dataset/test/X_test.txt", col.names = Features$Functions)
Y_test <- read.table("UCI HAR Dataset/test/y_test.txt", col.names = "Code")
Subject_train <- read.table("UCI HAR Dataset/train/subject_train.txt", col.names = "Subject")
X_train <- read.table("UCI HAR Dataset/train/X_train.txt", col.names = Features$Functions)
Y_train <- read.table("UCI HAR Dataset/train/y_train.txt", col.names = "Code")
x <- rbind(X_train, X_test)
y <- rbind(Y_train, Y_test)
subject <- rbind(Subject_train, Subject_test)
MergedData <- cbind(subject, y, x)
CleanData <- MergedData %>% select(Subject, Code, contains("mean"), contains("std"))
CleanData$Code <- Activities[CleanData$Code, 2]
names(CleanData)[2] = "activity"
names(CleanData)<-gsub("Acc", "Accelerometer", names(CleanData))
names(CleanData)<-gsub("Gyro", "Gyroscope", names(CleanData))
names(CleanData)<-gsub("BodyBody", "Body", names(CleanData))
names(CleanData)<-gsub("Mag", "Magnitude", names(CleanData))
names(CleanData)<-gsub("^t", "Time", names(CleanData))
names(CleanData)<-gsub("^f", "Frequency", names(CleanData))
names(CleanData)<-gsub("tBody", "TimeBody", names(CleanData))
names(CleanData)<-gsub("-mean()", "Mean", names(CleanData), ignore.case = TRUE)
names(CleanData)<-gsub("-std()", "STD", names(CleanData), ignore.case = TRUE)
names(CleanData)<-gsub("-freq()", "Frequency", names(CleanData), ignore.case = TRUE)
names(CleanData)<-gsub("angle", "Angle", names(CleanData))
names(CleanData)<-gsub("gravity", "Gravity", names(CleanData))
Final <- CleanData %>% group_by(Subject, activity) %>% summarise_all(funs(mean))
write.table(Final, "Final.txt", row.name=FALSE)
